task: Cifar10
synthesizer: Pattern


batch_size: 64
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs: 800
poison_epoch: 200
poison_epoch_stop: 220
save_on_epochs: [30, 50, 100, 105, 200, 205, 300, 305, 400, 405, 500, 550, 600, 650, 700, 750, 790, 800]
optimizer: SGD
log_interval: 100

poisoning_proportion: 0.2
backdoor_label: 8

resume_model: #resume_model/model_epoch_200.pt.tar

save_model: True
log: True

transform_train: True

fl: True
fl_no_models: 10
fl_local_epochs: 2
fl_poison_epochs: 15
fl_total_participants: 100
fl_eta: 1 # 0.8
fl_sample_dirichlet: True
fl_dirichlet_alpha: 0.9

fl_number_of_adversaries: 0
fl_weight_scale: 5
fl_adv_group_size: 5
# fl_single_epoch_attack: 200

attack: ThrDFed
defense: 'FedAvg'
fl_num_neurons: 5
noise_mask_alpha: 0 # 0.5
lagrange_step: 0.1
